"""
🚀 Model Deployment — generates FastAPI app + Dockerfile for one-click deploy.
Fixes: sanitises feature names (², spaces, special chars) for valid Python identifiers.
"""
import io
import json
import os
import pickle
import re
import zipfile
from typing import Dict, List
import pandas as pd
from utils.config import MODEL_DIR
from utils.logger import get_logger

logger = get_logger(__name__)


def _safe_field(name: str) -> str:
    """Convert any feature name to a valid Python identifier for Pydantic."""
    s = name
    # Replace unicode superscripts / special chars with ascii equivalents
    s = s.replace("²", "_sq").replace("³", "_cu").replace("×", "_x")
    s = s.replace(" ", "_").replace("-", "_").replace("/", "_per_")
    s = s.replace("(", "").replace(")", "").replace(".", "_")
    # Remove any remaining non-alphanumeric/underscore chars
    s = re.sub(r"[^\w]", "_", s)
    # Must not start with a digit
    if s and s[0].isdigit():
        s = "f_" + s
    return s.strip("_") or "feature"


class ModelExporter:
    def __init__(self, model, feature_names: List[str],
                 problem_type: str, target_col: str, model_name: str):
        self.model = model
        self.feature_names = feature_names          # original names
        self.safe_names   = [_safe_field(f) for f in feature_names]   # valid Python ids
        self.problem_type = problem_type
        self.target_col   = target_col
        self.model_name   = model_name

    def generate_fastapi_code(self) -> str:
        # Build field definitions: safe_field_name: float = Field(..., alias="original name")
        field_lines = []
        for orig, safe in zip(self.feature_names, self.safe_names):
            if orig == safe:
                field_lines.append(f"    {safe}: float")
            else:
                field_lines.append(f'    {safe}: float  # original: "{orig}"')

        feat_schema  = "\n".join(field_lines)
        orig_list    = json.dumps(self.feature_names,  indent=4)
        safe_list    = json.dumps(self.safe_names,     indent=4)
        predict_call = ("model.predict_proba(X)[0].tolist()"
                        if self.problem_type == "classification"
                        else "float(model.predict(X)[0])")
        predict_key  = ("probabilities" if self.problem_type == "classification"
                        else "prediction")
        resp_type    = "List[float]" if self.problem_type == "classification" else "float"

        return f'''"""
FastAPI prediction service — generated by AI Data Intelligence Copilot
Model        : {self.model_name}
Target       : {self.target_col}
Problem type : {self.problem_type}
Generated    : auto
"""
import pickle
import numpy as np
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import List

app = FastAPI(
    title="AI Copilot — {self.model_name}",
    description="Auto-generated prediction API for target: {self.target_col}",
    version="1.0.0",
)

with open("model.pkl", "rb") as f:
    model = pickle.load(f)

# Original feature names (used to build the numpy array in order)
ORIGINAL_FEATURES = {orig_list}

# Safe Python field names (used in Pydantic model)
SAFE_FEATURES = {safe_list}

FEATURE_MAP = dict(zip(SAFE_FEATURES, ORIGINAL_FEATURES))


class InputFeatures(BaseModel):
{feat_schema}

class PredictionResponse(BaseModel):
    {predict_key}: {resp_type}
    model_name: str
    features_used: List[str]
    input_received: dict

@app.get("/")
def root():
    return {{"message": "AI Copilot Prediction API is running",
            "model": "{self.model_name}",
            "target": "{self.target_col}",
            "problem_type": "{self.problem_type}",
            "n_features": len(ORIGINAL_FEATURES)}}

@app.get("/health")
def health():
    return {{"status": "healthy", "model_loaded": model is not None}}

@app.get("/features")
def get_features():
    return {{
        "original_names": ORIGINAL_FEATURES,
        "field_names":    SAFE_FEATURES,
        "n_features":     len(ORIGINAL_FEATURES),
        "target":         "{self.target_col}",
    }}

@app.get("/schema")
def get_schema():
    """Returns the expected input schema with field descriptions."""
    return {{
        "fields": [
            {{"field": s, "original": o, "type": "float"}}
            for s, o in zip(SAFE_FEATURES, ORIGINAL_FEATURES)
        ]
    }}

@app.post("/predict", response_model=PredictionResponse)
def predict(data: InputFeatures):
    try:
        values = [getattr(data, s) for s in SAFE_FEATURES]
        X = np.array([values])
        result = {predict_call}
        return PredictionResponse(
            {predict_key}=result,
            model_name="{self.model_name}",
            features_used=ORIGINAL_FEATURES,
            input_received=dict(zip(ORIGINAL_FEATURES, values)),
        )
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Prediction error: {{str(e)}}")

@app.post("/predict_batch")
def predict_batch(rows: List[InputFeatures]):
    """Predict for multiple rows at once."""
    try:
        X = np.array([[getattr(r, s) for s in SAFE_FEATURES] for r in rows])
        if "{self.problem_type}" == "classification":
            results = model.predict_proba(X).tolist()
            preds   = model.predict(X).tolist()
            return {{"probabilities": results, "predictions": preds,
                    "n_rows": len(rows), "model": "{self.model_name}"}}
        else:
            preds = model.predict(X).tolist()
            return {{"predictions": preds, "n_rows": len(rows),
                    "model": "{self.model_name}"}}
    except Exception as e:
        raise HTTPException(status_code=400, detail=str(e))

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000, reload=True)
'''

    def generate_dockerfile(self) -> str:
        return '''FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

COPY requirements_api.txt .
RUN pip install --no-cache-dir -r requirements_api.txt

COPY model.pkl .
COPY main.py .

EXPOSE 8000

HEALTHCHECK --interval=30s --timeout=10s --retries=3 \\
  CMD curl --fail http://localhost:8000/health || exit 1

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
'''

    def generate_requirements(self) -> str:
        return """fastapi>=0.110.0
uvicorn[standard]>=0.29.0
pydantic>=2.0.0
numpy>=1.26.0
scikit-learn>=1.4.0
xgboost>=2.0.0
lightgbm>=4.3.0
"""

    def generate_docker_compose(self) -> str:
        return f"""version: "3.9"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MODEL_NAME={self.model_name}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
"""

    def generate_env_example(self) -> str:
        return f"""# AI Copilot API — Environment Variables
MODEL_NAME={self.model_name}
TARGET_COL={self.target_col}
PROBLEM_TYPE={self.problem_type}
HOST=0.0.0.0
PORT=8000
"""

    def generate_test_script(self) -> str:
        """Python test script that validates the API."""
        sample = {s: 0.0 for s in self.safe_names}
        return f"""#!/usr/bin/env python3
\"\"\"
Auto-generated API test script.
Run: python test_api.py
\"\"\"
import requests, json, sys

BASE = "http://localhost:8000"

def test_health():
    r = requests.get(f"{{BASE}}/health")
    assert r.status_code == 200
    print("✅ Health check passed")

def test_features():
    r = requests.get(f"{{BASE}}/features")
    assert r.status_code == 200
    data = r.json()
    print(f"✅ Features endpoint: {{data['n_features']}} features")

def test_predict():
    payload = {json.dumps(sample, indent=4)}
    r = requests.post(f"{{BASE}}/predict",
                      headers={{"Content-Type": "application/json"}},
                      json=payload)
    assert r.status_code == 200, f"FAIL: {{r.text}}"
    result = r.json()
    print(f"✅ Predict endpoint: {{result}}")

def test_schema():
    r = requests.get(f"{{BASE}}/schema")
    assert r.status_code == 200
    print(f"✅ Schema endpoint returned {{len(r.json()['fields'])}} fields")

if __name__ == "__main__":
    print("Testing API at", BASE)
    try:
        test_health()
        test_features()
        test_schema()
        test_predict()
        print("\\n🎉 All tests passed!")
    except Exception as e:
        print(f"\\n❌ Test failed: {{e}}")
        sys.exit(1)
"""

    def generate_readme(self) -> str:
        safe_sample = {s: 1.0 for s in self.safe_names[:5]}
        return f"""# 🚀 AI Copilot — Prediction API

Auto-generated by **AI Data Intelligence Copilot**

| Property | Value |
|----------|-------|
| Model | **{self.model_name}** |
| Target | **{self.target_col}** |
| Problem Type | **{self.problem_type}** |
| Features | **{len(self.feature_names)}** |

---

## Quick Start

### Option 1 — Docker (recommended)
```bash
docker build -t copilot-api .
docker run -p 8000:8000 copilot-api
```

### Option 2 — Docker Compose
```bash
docker-compose up
```

### Option 3 — Local Python
```bash
pip install -r requirements_api.txt
uvicorn main:app --host 0.0.0.0 --port 8000 --reload
```

---

## API Endpoints

| Method | Endpoint | Description |
|--------|----------|-------------|
| GET | `/` | API info |
| GET | `/health` | Health check |
| GET | `/features` | Feature list |
| GET | `/schema` | Input schema |
| POST | `/predict` | Single prediction |
| POST | `/predict_batch` | Batch predictions |

Interactive docs: **http://localhost:8000/docs**

---

## Example — Single Prediction

```bash
curl -X POST http://localhost:8000/predict \\
  -H "Content-Type: application/json" \\
  -d '{json.dumps(safe_sample)}'
```

## Example — Batch Prediction

```python
import requests
rows = [{json.dumps(safe_sample)}, ...]
r = requests.post("http://localhost:8000/predict_batch", json=rows)
print(r.json())
```

---

## Features ({len(self.feature_names)} total)

| Field Name | Original Name |
|-----------|--------------|
{chr(10).join(f"| `{s}` | `{o}` |" for s,o in zip(self.safe_names, self.feature_names))}

---

## Cloud Deployment

### Railway
```bash
railway up
```

### Render
Push to GitHub → connect to Render → set start command: `uvicorn main:app --host 0.0.0.0 --port $PORT`

### Google Cloud Run
```bash
gcloud builds submit --tag gcr.io/PROJECT/copilot-api
gcloud run deploy --image gcr.io/PROJECT/copilot-api --platform managed
```

### AWS EC2
```bash
sudo docker build -t copilot-api .
sudo docker run -d -p 80:8000 copilot-api
```
"""

    def generate_sample_request(self) -> Dict:
        """Return sample request body using safe field names."""
        return {s: 0.0 for s in self.safe_names}

    def generate_sample_request_original(self) -> Dict:
        """Return sample using original feature names (for documentation)."""
        return {f: 0.0 for f in self.feature_names}

    def export_zip(self) -> bytes:
        """Bundle everything into a ready-to-deploy zip."""
        buf = io.BytesIO()
        with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
            # Serialise model
            model_buf = io.BytesIO()
            pickle.dump(self.model, model_buf)
            zf.writestr("model.pkl", model_buf.getvalue())
            # All code & config files
            zf.writestr("main.py",               self.generate_fastapi_code())
            zf.writestr("Dockerfile",             self.generate_dockerfile())
            zf.writestr("docker-compose.yml",     self.generate_docker_compose())
            zf.writestr("requirements_api.txt",   self.generate_requirements())
            zf.writestr("test_api.py",            self.generate_test_script())
            zf.writestr("README.md",              self.generate_readme())
            zf.writestr(".env.example",           self.generate_env_example())
        buf.seek(0)
        return buf.read()
